### ISSUE TITLE
Setup Requirements.txt

### ISSUE THREAD

**Issue by GantMan** [GantMan/proselyte#3]
These projects are all over the place with requirements, make life easy with a requirements.txt setup like the readme says.

Then update the readme to say it actually works.

**Comment by csp33** [comment]
I would like to work on this!

**Comment by GantMan** [comment]
@csp98 - I got someone who messaged me directly who also asked for this (right before you).

Can I interest you in another ticket perhaps?   Do you like the idea of the project?

**Comment by GantMan** [comment]
merged!!!
