### ISSUE TITLE
Fix Model.py parameters

### ISSUE THREAD

**Issue by GantMan** [GantMan/proselyte#6]
$ python model.py <path to keras file> <path to temp folder>

### The first parameter *$1*
This points model.py to the file to convert.  For now, we are doing only Keras, but note that in the future this could be a caffe file or other.  This will set the file path to convert.

### The second parameter *$2*
This points to the temp folder that can be used.  Inside here, other folders can be created and then cleaned up during the conversion process.

The result will be stored in `$2/results/result.zip`.  Leave behind the original Keras file and the results.zip, the model.py should clean up everything else it created in the temp folder.

**Comment by janlehky** [comment]
Hi,

 I am thinking about using standard argparse. Is it ok for you? Or you have something else in mind?

**Comment by GantMan** [comment]
standard arg parse works for me!
